### PR TITLE
Added checkbox "Loop through prompts (if fewer prompts than models)".…

### PR DESCRIPTION
**Pull request by RandyHaylor**
Added checkbox "Loop through prompts (if fewer prompts than models). If unchecked, model and prompt list must be the same length.

The base behavior is identical, but if this box is checked, it will just loop through the one or more prompts as needed to satisfy the prompt list and run the generations.  This will let me just enter one prompt and test it against a bunch of models.

An interesting idea could be an iterator tag like [i=1++] that the code would recognize and increment in the loop (as in if you have a bunch of lora training checkpoints to compare).  I might do that soon, as that's something I want to automate. Easy way to quickly find out when a lora is overtrained without having to manually run a bazillion generations manually...

### CODE REVIEW

**Comment by h43lb1t0** [comment]
It seems like some people want this. Okay.
But a few things:

- Iterator isn't imported from typing. 
- please move the checkbox in the advanced settings
- add informations about this in the HelpBatchCheckpointsPrompt.md

and for future PRs please use a dev branch :)

**Comment by RandyHaylor** [comment]
Cool! I actually just set up a cool iterator from the prompt. What I added here is just a check box to allow a lower number of prompts to repeat.

I'll put this and that in a more cleaned up push. 

I've been wanting this sort of functionality and I'm stoked your script is such a good platform.

**Comment by h43lb1t0** [comment]
Hi, i've changed a few things in the BatchParams file. Nothings that will brake your new stuff, but probably won't merge without a conflict. Would be nice if you could switch to the dev branch and copy your changes/solve the merge conflict.

**Comment by RandyHaylor** [comment]
Sounds good! I got caught up in setting up a small parser for some basic functions.  My footprint in your code is very small so it will be fine no matter what.

**Comment by h43lb1t0** [comment]
is this ready to merge?

**Comment by RandyHaylor** [comment]
https://github.com/RandyHaylor/SD-WebUI-BatchCheckpointPrompt/tree/dev

I added a bit more functionality in.  Also adds custom iterator via a basic scripting tag in the prompt i.e. [0.2,myIncrementor,+=,0.05]  

Lets not apply this one as my dev branch also has this change and they affect some of the same lines.

I'll see if I can get another pull request set up.

**Comment by h43lb1t0** [comment]
I've cloned your dev branch. I can't get any of your functions to work.
Also `if enable_iterators:
            process_variables_from_prompts(prompts)` return a list, that is not used?

**Comment by RandyHaylor** [comment]
process_variables_from_prompts(prompts) is a function that looks for custom tags to process as iterators.

have a look at the pull request I just made, I synced first then re-applied my additions. It was working for me today.  the pull request has more details and examples.

way past my bedtime btw, logging off for the night.

**Comment by RandyHaylor** [comment]
> I've cloned your dev branch. I can't get any of your functions to work.
> 
> Also `if enable_iterators:
> 
>             process_variables_from_prompts(prompts)` return a list, that is not used?

Ah prompts is a reference to an object and it updates it. I agree it would be better coding to edit a copy and return a reference to that, but it does work to edit the prompt collection.

**Pull request closed without merging**
